require_relative "test_helper"

class CompletionScriptTest < Minitest::Test
  def test_each_shell_calls_and_registers_the_binary
    registrations = {
      bash: "complete -F _usage_complete_mise 'mise'",
      fish: "complete -c 'mise' -f -a '(__usage_complete_mise)'",
      nu: "$env.config.completions.external.completer = {|spans|",
      powershell: "Register-ArgumentCompleter -Native -CommandName 'mise'",
      zsh: "compdef _mise 'mise'"
    }
    registrations.each do |shell, registration|
      script = Usage::Complete::Script.new("mise", shell).render

      assert_includes script, "mise __complete_word__ --shell #{shell}"
      assert_includes script, registration
      expected = "# @generated by usage for `mise __complete_word__ --shell #{shell}`"
      expected = "#compdef mise\n#{expected}" if shell == :zsh
      assert script.start_with?(expected), shell
      refute_match(/\{(?:bin|ident)\}/, script)
    end
  end

  def test_scripts_handle_every_path_marker
    assert_equal({
      any: "\x01files", commands: "\x01commands", dirs: "\x01dirs", executables: "\x01executables"
    }, Usage::Complete::MARKERS)
    bash = script(:bash)
    zsh = script(:zsh)
    %w[files dirs executables commands].each do
      assert_includes bash, "$'\\001#{_1}'"
      assert_includes zsh, "$'\\001#{_1}'"
    end

    assert_includes script(:fish), "printf '\\x01files'"
    assert_includes script(:fish), 'test -d "$value"; or test -x "$value"'
    assert_includes zsh, "_files -g '*(-/,*)'"
    assert_includes script(:nu), '"\\u{1}"'
    powershell = script(:powershell)
    assert_includes powershell, "[char]1"
    assert_includes powershell, "-CommandType Application, ExternalScript"
    assert_includes powershell, "} elseif ($files) {"
    refute_includes powershell, "} else if ($files) {"
  end

  def test_scripts_delegate_command_completion_to_the_shell
    {
      bash: "compgen -c",
      fish: "__fish_complete_command",
      nu: "which",
      powershell: "Get-Command",
      zsh: "_command_names"
    }.each do |shell, expected|
      assert_includes script(shell), expected
    end
  end

  def test_fish_prints_option_like_candidates_safely
    output = script(:fish)

    refute_includes output, "echo $entry"
    assert_includes output, "printf '%s\\n' $entry"
  end

  def test_nu_preserves_path_and_windows_command_semantics
    output = script(:nu)

    refute_includes output, "| commandline complete"
    assert_includes output, "let wants_path_fallback"
    assert_includes output, '$nu.os-info.name == "windows"'
  end

  def test_nu_chains_the_existing_completer
    output = script(:nu)

    assert_includes output, "let __usage_previous_mise = ($env.config.completions.external.completer? | default null)"
    assert_includes output, "$env.config.completions.external.completer = {|spans|"
    assert_includes output, 'if ($spans | get 0) == "mise"'
    assert_includes output, "do $__usage_previous_mise $spans"
  end

  def test_nu_identifiers_do_not_collapse
    dashed = Usage::Complete::Script.new("foo-bar", :nu).render
    plus = Usage::Complete::Script.new("foo+bar", :nu).render
    escaped = Usage::Complete::Script.new("foo_x2dbar", :nu).render

    assert_includes dashed, "__usage_complete_foo_x2dbar"
    refute_includes plus, "__usage_complete_foo_x2dbar"
    refute_includes escaped, "__usage_complete_foo_x2dbar"
    assert_includes Usage::Complete::Script.new("foo-bar", :bash).render, "_usage_complete_foo-bar()"
  end

  def test_invalid_binary_and_shell_are_rejected
    ["", "my cli", "it's", "a;b", "a$b"].each do |bin|
      assert_raises(ArgumentError) { Usage::Complete::Script.new(bin, :bash) }
    end
    %w[mise foo-bar foo_bar foo.bar g++ 7zip].each do
      Usage::Complete::Script.new(_1, :bash)
    end
    assert_raises(ArgumentError) { Usage::Complete::Script.new("mise", :tcsh) }
  end

  def test_zsh_supports_sourcing_and_fpath_autoloading
    output = script(:zsh)

    assert output.start_with?("#compdef mise\n")
    assert_includes output, 'if [ "$funcstack[1]" = "_mise" ]; then'
    assert_includes output, "compdef _mise 'mise'"
  end

  private

  def script(shell)
    Usage::Complete::Script.new("mise", shell).render
  end
end
